# Generated by Django 4.2.16 on 2024-12-25 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bslogic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('peso', models.CharField(max_length=255)),
                ('numero_bultos', models.IntegerField()),
                ('coste_adecuacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservado_a', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_inicial', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_final', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListadoActuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actuacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bslogic.actuacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bslogic.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='nombre',
        ),
        migrations.AddField(
            model_name='almacen',
            name='almacen',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='laboratorio',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Accion',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TipoDeAccion',
        ),
        migrations.DeleteModel(
            name='TipoDeProducto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bslogic.almacen'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bslogic.estado'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bslogic.tipo'),
        ),
    ]
