# Generated by Django 5.0.7 on 2025-01-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bslogic', '0002_actuacion_empresa_estado_inventario_listadoactuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='etiqueta',
            field=models.CharField(default='-1', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ListadoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bslogic.inventario')),
            ],
        ),
    ]
