# Generated by Django 5.0.7 on 2025-01-11 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bslogic', '0003_inventario_etiqueta_listadodocumentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bslogic.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bslogic.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='empleados',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bslogic.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bslogic.empresa'),
            preserve_default=False,
        ),
    ]
