# Generated by Django 4.2.16 on 2025-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bslogic', '0005_listadodocumentos_datos_del_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadoactuacion',
            name='descripcion',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
