# Generated by Django 4.2.16 on 2025-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bslogic', '0006_listadoactuacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacion',
            name='actuacion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='etiqueta',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('almacen', 'laboratorio')},
        ),
    ]
