# Generated by Django 4.2.16 on 2025-03-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bslogic', '0007_alter_actuacion_actuacion_alter_empresa_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editor', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
